# Generated by Django 2.2.10 on 2022-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20221021_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('success', 'Create'), ('warning', 'Update'), ('danger', 'Delete'), ('info', 'Close')], default='success', max_length=20)),
                ('target_model', models.CharField(default='', max_length=20)),
                ('detail', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
