# Generated by Django 2.2.10 on 2022-10-22 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerindent',
            name='employees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Profile', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='customerindent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CustomerModel', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='customerindent',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.FactoryModel', verbose_name='工厂'),
        ),
        migrations.AlterField(
            model_name='customerindent',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.GoodsModel', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='factoryindent',
            name='employees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Profile', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='factoryindent',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.FactoryModel', verbose_name='工厂'),
        ),
        migrations.AlterField(
            model_name='factoryindent',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.GoodsModel', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='feedbackindent',
            name='customer_indent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CustomerIndent', verbose_name='顾客订单'),
        ),
        migrations.AlterField(
            model_name='feedbackindent',
            name='employees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Profile', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='电话号码'),
        ),
    ]
