# Generated by Django 2.2.10 on 2022-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20221022_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerindent',
            name='customer',
            field=models.CharField(max_length=20, verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='customerindent',
            name='employees',
            field=models.CharField(max_length=20, verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='customerindent',
            name='factory',
            field=models.CharField(max_length=20, verbose_name='工厂'),
        ),
        migrations.AlterField(
            model_name='customerindent',
            name='good',
            field=models.CharField(max_length=20, verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='factoryindent',
            name='employees',
            field=models.CharField(max_length=20, verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='factoryindent',
            name='factory',
            field=models.CharField(max_length=20, verbose_name='工厂'),
        ),
        migrations.AlterField(
            model_name='factoryindent',
            name='good',
            field=models.CharField(max_length=20, verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='feedbackindent',
            name='customer_indent',
            field=models.CharField(max_length=20, verbose_name='顾客订单'),
        ),
        migrations.AlterField(
            model_name='feedbackindent',
            name='employees',
            field=models.CharField(max_length=20, verbose_name='员工'),
        ),
    ]
