# Generated by Django 2.2.10 on 2022-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20221022_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='factory',
            field=models.CharField(max_length=20, verbose_name='工厂'),
        ),
    ]
