# Generated by Django 2.2.10 on 2022-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20221022_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='vip_level',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='VIP等级'),
        ),
    ]
