# Generated by Django 2.2.10 on 2022-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20221022_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别'),
        ),
    ]
