# Generated by Django 2.2.10 on 2022-10-22 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20221022_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='namex',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
