# Generated by Django 2.2.10 on 2022-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20221023_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别'),
        ),
    ]
