# Generated by Django 2.2.10 on 2022-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20221023_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerindent',
            name='status',
            field=models.IntegerField(choices=[(0, '已创建'), (1, '已付款'), (2, '已完成')], verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='feedbackindent',
            name='status',
            field=models.IntegerField(choices=[(0, '回访'), (1, '投诉')], verbose_name='状态'),
        ),
    ]
